"""initial schema

Revision ID: c4468d16bf57
Revises: 
Create Date: 2026-09-03 18:58:16.440446
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'c4468d16bf57'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='organization_id_user_id')
    )
    op.create_index('ix_org_members_user', 'organization_members', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('max_rows', sa.Integer(), nullable=False),
    sa.Column('query_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workspaces_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('organization_id', 'slug', name='organization_id_slug')
    )
    op.create_table('database_connections',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('ssl_mode', sa.String(length=20), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('allowed_schemas', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('query_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_rows', sa.Integer(), nullable=False),
    sa.Column('allow_sample_values', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_database_connections_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_database_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_connections')),
    sa.UniqueConstraint('workspace_id', 'name', name='workspace_id_name')
    )
    op.create_index('ix_database_connections_workspace', 'database_connections', ['workspace_id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('clarification_count', sa.Integer(), nullable=False),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_usage_metrics_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_metrics'))
    )
    op.create_index('ix_usage_metrics_workspace_day', 'usage_metrics', ['workspace_id', 'day'], unique=True)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='workspace_id_user_id')
    )
    op.create_index('ix_workspace_members_user', 'workspace_members', ['user_id'], unique=False)
    op.create_table('business_glossary',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('maps_to', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_business_glossary_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_business_glossary_database_id_database_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_glossary')),
    sa.UniqueConstraint('database_id', 'term', name='database_id_term')
    )
    op.create_table('conversations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_conversations_database_id_database_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_workspace_created', 'conversations', ['workspace_id', 'created_at'], unique=False)
    op.create_table('database_tables',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_rows', sa.BigInteger(), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('foreign_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indexes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_document', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_database_tables_database_id_database_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_tables')),
    sa.UniqueConstraint('database_id', 'schema_name', 'table_name', name='database_id_schema_name_table_name')
    )
    op.create_index('ix_database_tables_database', 'database_tables', ['database_id'], unique=False)
    op.create_table('saved_queries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_saved_queries_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_saved_queries_database_id_database_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_saved_queries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queries'))
    )
    op.create_index('ix_saved_queries_workspace', 'saved_queries', ['workspace_id'], unique=False)
    op.create_table('clarifications',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_clarifications_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_clarifications_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clarifications'))
    )
    op.create_table('queries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('executed_sql', sa.Text(), nullable=True),
    sa.Column('query_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tables_used', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('assumptions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('required_clarification', sa.Boolean(), nullable=False),
    sa.Column('was_blocked', sa.Boolean(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=True),
    sa.Column('explain_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visualization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_queries_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_queries_database_id_database_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_queries_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_queries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries'))
    )
    op.create_index('ix_queries_database_created', 'queries', ['database_id', 'created_at'], unique=False)
    op.create_index('ix_queries_hash', 'queries', ['query_hash'], unique=False)
    op.create_index('ix_queries_workspace_created', 'queries', ['workspace_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], name=op.f('fk_audit_logs_database_id_database_connections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_audit_logs_query_id_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_logs_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_event', 'audit_logs', ['event'], unique=False)
    op.create_index('ix_audit_logs_workspace_created', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_messages_query_id_queries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_audit_logs_workspace_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_queries_workspace_created', table_name='queries')
    op.drop_index('ix_queries_hash', table_name='queries')
    op.drop_index('ix_queries_database_created', table_name='queries')
    op.drop_table('queries')
    op.drop_table('clarifications')
    op.drop_index('ix_saved_queries_workspace', table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index('ix_database_tables_database', table_name='database_tables')
    op.drop_table('database_tables')
    op.drop_index('ix_conversations_workspace_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('business_glossary')
    op.drop_index('ix_workspace_members_user', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_usage_metrics_workspace_day', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index('ix_database_connections_workspace', table_name='database_connections')
    op.drop_table('database_connections')
    op.drop_table('workspaces')
    op.drop_index('ix_org_members_user', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
